# Generated by Django 2.0.5 on 2018-05-16 19:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='address_city',
            field=models.CharField(blank=True, help_text='ex. Philadelphia', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='address_name',
            field=models.CharField(blank=True, help_text="Ex. John's Pizzeria", max_length=100),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='address_state',
            field=models.CharField(blank=True, help_text='ex. PA', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='address_street',
            field=models.CharField(blank=True, help_text='ex. 123 E South St.', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='address_zip',
            field=models.CharField(blank=True, help_text='ex. 19140', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='describe the event'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='An attractive image that represents the event. Avoid images with text.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='type',
            field=models.CharField(choices=[('AVS', 'AVS'), ('Other', 'Other')], help_text='Is this an official AVS event?', max_length=100),
        ),
    ]
