# Generated by Django 2.0.5 on 2018-05-15 17:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField((('events_list', wagtail.core.blocks.StructBlock(())), ('cta', wagtail.core.blocks.StructBlock((('headline', wagtail.core.blocks.CharBlock(help_text='A brief demand with a verb.', max_length=100)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Upload an image to show alongside the call-to-action.')), ('tagline', wagtail.core.blocks.CharBlock(help_text='One sentence about what users can expect once they click the button.', max_length=255)), ('button_text', wagtail.core.blocks.CharBlock(help_text="A verb for the user's action. 1-3 words.", max_length=50)), ('button_url', wagtail.core.blocks.URLBlock(help_text='The target location of the button. ex. https://americanvegan.org/my-page/', label='Button URL'))))), ('portal', wagtail.core.blocks.StructBlock(())), ('quote', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(help_text='Into text to this quote, including the name of the speaker.', max_length=100, required=False)), ('quote', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], help_text="The text of the quotation. Include the name of the speaker if it's not in the title")), ('button_text', wagtail.core.blocks.CharBlock(help_text="A verb for the user's action. Ex. Learn more about...", max_length=100)), ('button_url', wagtail.core.blocks.URLBlock(help_text='The target location of the button. ex. https://americanvegan.org/my-page/', label='Button URL')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Upload an image to show alongside the quote.'))))), ('featured_pages', wagtail.core.blocks.StructBlock((('pages', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(help_text='Select the pages you would like to highlight'))), ('button_text', wagtail.core.blocks.CharBlock(help_text="A verb for the user's action. Ex. Learn more about...", max_length=100)), ('button_url', wagtail.core.blocks.URLBlock(help_text='The target location of the button. ex. https://americanvegan.org/my-page/', label='Button URL'))))), ('magazines', wagtail.core.blocks.StructBlock(()))), default=''),
            preserve_default=False,
        ),
    ]
