# Generated by Django 2.0.5 on 2018-08-11 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('info_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='listing_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
