# Generated by Django 2.0.5 on 2018-05-16 19:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0019_delete_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RecipePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('prep_time', models.CharField(blank=True, help_text='How long will it take to prepare the ingredients?', max_length=100)),
                ('cook_time', models.CharField(blank=True, help_text='How much oven or stove time is involved?', max_length=100)),
                ('servings', models.CharField(blank=True, help_text='How many humans can this recipe serve?', max_length=100)),
                ('ingredients', wagtail.core.fields.RichTextField(blank=True, help_text='List the ingredients, and their amounts.')),
                ('directions', wagtail.core.fields.RichTextField(blank=True, help_text='Describe the steps to this recipe in detail.')),
                ('image', models.ForeignKey(blank=True, help_text='A mouth-watering picture of the recipe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
