# Generated by Django 2.0.5 on 2018-05-16 19:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtaildocs', '0007_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MagazinePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('published_date', models.DateField(blank=True, help_text='Date this issue was originally published.')),
                ('description', wagtail.core.fields.RichTextField(blank=True, help_text='Additional information about this issue.')),
                ('public', models.BooleanField(default=False, help_text='By default, the PDF version is available to members only. Enable this to allow anyone to download the PDF.')),
                ('file', models.ForeignKey(help_text='PDF version of this issue.', on_delete=django.db.models.deletion.PROTECT, to='wagtaildocs.Document')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
